[#function getAssetTitle asset title]
    [#assign linkText = ""]
    [#if asset?has_content]
        [#if title?has_content]
            [#assign linkText = title]
        [#elseif asset.title?has_content]
            [#assign linkText = asset.title]
        [#elseif asset.subject?has_content]
            [#assign linkText = asset.subject]
        [#-- [#elseif asset.description?has_content]
            [#assign linkText = asset.description]	 --]
        [#elseif asset.caption?has_content]
            [#assign linkText = asset.caption]
        [#elseif asset.fileName?has_content]
            [#assign linkText = asset.fileName]
        [#elseif asset.name?has_content]
            [#assign linkText = asset.name]
        [#else]
            [#assign linkText = ""]
        [/#if]
    [/#if]
    [#return linkText]
[/#function]

[#-- function: string value file size --]
[#function getAssetFileSizeString assetFileSize]
    [#if assetFileSize > 999999]
        [#assign typeFileSize = " mb"]
        [#assign operatorValue = 1024000]
    [#else]
        [#assign typeFileSize = " kb"]
        [#assign operatorValue = 1024]
    [/#if]
    [#assign valueFileSize = (assetFileSize/operatorValue)?ceiling]
    [#assign value = valueFileSize + typeFileSize]
    [#return value]
[/#function]

[#function getVariation uuid variation]
    [#assign returnAssetLink = ""]
    [#if uuid?has_content]
        [#assign asset = damfn.getAsset(uuid)!]
        [#if asset?has_content]
            [#assign returnAssetLink = damfn.getAssetLink(asset, variation)!]
        [/#if]
    [/#if]
    [#return returnAssetLink]
[/#function]
