[#assign linkHref = ""]
[#assign linkText = ""]

[#if item[field + 'internal']?has_content]
    [#assign contentPage = cmsfn.nodeById(item[field + 'internal']!"")!""]
    [#if contentPage?has_content]
    [#--[#if !cmsfn.asJCRNode(contentPage).hasProperty("mgnl:deleted")]--]
        [#assign linkHref = cmsfn.link(contentPage)!]
        [#assign linkText = item['title' + field]!item['title' + field?cap_first]!contentPage.title!i18n['link.label']!]
    [#--[/#if]--]

    [#-- load page properties --]

        [#assign contentDetails = cmsfn.asContentMap(contentPage)]

        [#if !title?has_content]
            [#assign title = contentDetails.title!]
        [/#if]
        [#if !abstract?has_content]
            [#assign abstract = contentDetails.abstractList!]
        [/#if]
        [#if !abstract?has_content]
            [#assign abstract = contentDetails.abstract!]
        [/#if]
        [#if !image?has_content]
            [#assign image = contentDetails.imageList!]
        [/#if]
        [#if !image?has_content]
            [#assign image = contentDetails.image!]
        [/#if]
        [#if !imageMobile?has_content]
            [#assign imageMobile = contentDetails.imageListMobile!]
        [/#if]
        [#if !imageMobile?has_content]
            [#assign imageMobile = contentDetails.imageMobile!]
        [/#if]
        [#if !imageTablet?has_content]
            [#assign imageTablet = contentDetails.imageListTablet!]
        [/#if]
        [#if !imageTablet?has_content]
            [#assign imageTablet = contentDetails.imageTablet!]
        [/#if]
    [/#if]
[/#if]
